// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgcYTrHa9biSayYnxeRhAVrhrC3k93BS8',
    appId: '1:968899515096:web:d1f3474c3cbf668c69fdad',
    messagingSenderId: '968899515096',
    projectId: 'chatzy-882da',
    authDomain: 'chatzy-882da.firebaseapp.com',
    storageBucket: 'chatzy-882da.appspot.com',
    measurementId: 'G-ENE98KXYGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCC3CP_x_th1HuswovCJQdO0ZyCXje-u0',
    appId: '1:968899515096:android:03ae688e58ce8b9969fdad',
    messagingSenderId: '968899515096',
    projectId: 'chatzy-882da',
    storageBucket: 'chatzy-882da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSYy12-QGaFichjUXr1nVUY4SSaCdMe2c',
    appId: '1:968899515096:ios:b264a045d22bee7769fdad',
    messagingSenderId: '968899515096',
    projectId: 'chatzy-882da',
    storageBucket: 'chatzy-882da.appspot.com',
    iosClientId: '968899515096-ucaajera7j276e8gd9eog85ffdqmt6f0.apps.googleusercontent.com',
    iosBundleId: 'com.robertdocan.apps.chatzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSYy12-QGaFichjUXr1nVUY4SSaCdMe2c',
    appId: '1:968899515096:ios:b264a045d22bee7769fdad',
    messagingSenderId: '968899515096',
    projectId: 'chatzy-882da',
    storageBucket: 'chatzy-882da.appspot.com',
    iosClientId: '968899515096-ucaajera7j276e8gd9eog85ffdqmt6f0.apps.googleusercontent.com',
    iosBundleId: 'com.robertdocan.apps.chatzy',
  );
}
